name: build-docker-image

# Run workflow on push to main or manual trigger
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
        # Get git functionality
      - name: checkout
        uses: actions/checkout@v3

        # Setup docker hub credentials
      - name: authenticate docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        # Setup extended docker CLI with buildx plugin
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

        # Build docker image and push it to docker hub repository
      - name: build and push docker image to docker hub repository
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vocabversus-interface:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
        # Setup azure credentials
      # - name: authenticate azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      
        # Update deployed image on azure app service
      - name: deploy to azure
        uses: azure/webapps-deploy@v2
        with:
            app-name: 'vocabversus'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_a733e04350aa4f3c987e31928430a1e9 }}
            images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/vocabversus-interface:latest'